config/routes.rb
Riszil::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get '/robots.txt' => 'welcome#robots'
  get 'express_payment' => 'users#express_payment', :as => 'express_payment'
  post 'save_locations' => 'users#save_locations', :as => 'save_locations'

  resources :temp_locations do     
  end

  resources :locations do
    collection do
      post 'temp_import'
      get 'sample_csv'
      post 'process_payment'
      get 'express_checkout'     
      get 'express_payment' 
    end     
  end

  resource :referral_card, only: [:show] do
    post 'print'
  end

  resources :referals do
    collection do
      get 'search' , :action => 'search'
    end 

    member do
      post 'move' , :action => 'move'
      delete 'remove' , :action => 'remove'
    end
  end  

  resource :search , :only => [:none] do
      #post "users" ,:action => 'search'
      get "users" ,:action => 'search'
      get "suggestions" ,:action => 'suggestions'
  end  

  resources :skills do
    collection do
      get 'autocomplete' , :action => 'autocomplete'
    end  
  end  

  resources :barters , :only => [:index] do
    collection do
      get 'search'
    end  
  end  

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]  

  get '/profile/tips' => 'welcome#profile_tips', :as => 'profile_tips'
  #get '/contests_promotions' => 'welcome#contests_promotions', :as => 'contests_promotions'
  # get '/about' => 'welcome#about_us', :as => 'about_us'
  # get '/comming_soon' => 'welcome#comming_soon'
  get '/country/subregion_options' => 'welcome#subregion_options'

  get "schedule/new"

  get "photo/new"

  get "photo/create"

  get "photo/show"

  get "affiliate_programme" => redirect("/") # "welcome#affiliate_programme", :as => 'affiliate_programme'
  
  get "what_is_riszil" =>  "welcome#what_is_riszil", :as => 'what_is_riszil'

  get "passwords/edit" => "passwords#edit", :as => 'edit_password'
  put "passwords/update" => "passwords#update", :as => 'update_password'

  devise_for :users, :controllers => {:registrations => "newregistrations",:sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks"}
  
  resources :users,only:[:none] do
    member do
      post 'edit_referal'
      post 'update_referal'
    end
    resources :photos, :except => [:update, :edit] do
      member do
        post 'set_as_profile_photo' ,:action => 'set_as_profile_photo'
      end  
    end  
    resource :schedule
    member do
      post 'rate' , :action => 'rate'
      get 'report'
      #get "request_pay"
    end  
    collection do
      put 'post_feedback/:business_id' , :action => 'post_feedback' , :as => 'post_feedback'
    end
  end


  get 'membership' => "memberships#index", :as => 'membership'
  get 'membership/plans' => "memberships#new", :as => 'membership_plans'
  get 'membership/change' => "memberships#change", :as => 'change_membership'
  post 'membership/upgrade' => "memberships#upgrade", :as => 'upgrade_membership'
  get 'membership/express_checkout' => "memberships#express_checkout", :as => 'express_checkout_membership'
  get 'membership/process_payment' => "memberships#process_payment", :as => 'process_payment_membership'

  resources :invites, :only => [:new, :create] do
    collection do
      get 'preview'
    end
  end

  get 'invites/decline/:token' => "invites#decline", :as => 'decline_invite'

  resources :zipcodes do
    collection do
      get 'zip'
    end
  end
  
  #resources :affiliates 
  get "w9_form" => "affiliates#w9_form_detail"
  get "affiliate" => "affiliates#affiliate" 
  post "w9_form" => "affiliates#create_w9_form_detail"
  put "w9_form" => "affiliates#update_w9_form_detail" 
  get "contact_us" => "welcome#contact_us"
  post "send_visitor_info" => "welcome#send_visitor_info"

  root :to => "welcome#index"

  get "new_payment_detail" => "welcome#new_payment_detail"

  namespace :admin do
    get '/' => "users#dashboard" , :as => "root"
    get 'users' => "users#index" , :as => "users"
    get 'login' => "admins#login" , :as => "login" 
    get 'reward_transaction' => "admins#reward_transaction" , :as => "reward_transaction" 
              
    resources :email_verification_logs, only: [:index]           
    resources :affiliates
    resources :users do
      collection do
          get 'start_hubuco'
          get 'search',:action => "search" , :as => "search"  
          get 'import'
          get 'claimed'
          get 'recent'
          post 'upload_csv'            
      end        
      member do
          post 'pay_affiliation_reward',:action => "pay_affiliation_reward"
          put 'activate'
          put 'deactivate'
      end  
    end  
    resources :skills do
      collection do
        get 'search'
        post 'search'
        post 'merge'
        get 'new_merge'
      end
      member do
        delete 'force_destroy'
      end 
    end 
    resources :user_imports do
      collection do
        get 'failed'
      end  
      member do
        post 'retry'
      end        
    end     
  end  

  match 'fbhome',to: 'welcome#fbhome', via: [:get]

  # authenticated :user do
  #   get ":username" => "users#show", :as => 'user'
  # end

  # get ":username" => "welcome#index" , :as => 'user'

  get ":username" => "users#show", :as => 'user'

end

app/models/skill.rb
class Skill < ActiveRecord::Base
 require 'rubygems'
 require 'roo' 

  attr_accessible :name
  has_many :skill_users, :dependent => :destroy
  has_many :referals, :dependent => :destroy
  has_many :users , :through => :skill_users, :uniq => true

  validates :name, :presence => true 
  validates_uniqueness_of :name

  scope :offering , where("skill_users.offering_for_barter = ?",true) 

  # after_save :reindex_users!
  # # Reindex corresponding user only , instead of whole class.
  # def reindex_users!
  #     Sunspot.index! self.users
  # end  

  searchable do
     text :name, :as => :user_skill
     integer :id
  end 

  def merge!(skill_ids)
    skill_ids = skill_ids.compact.uniq - [self.id]
    to_skills = Skill.includes(:skill_users, :referals).where(id: skill_ids)
      
    skill_user_ids = to_skills.map(&:skill_user_ids).flatten.compact.uniq
    referal_ids = to_skills.map(&:referal_ids).flatten.compact.uniq

    skill_users = SkillUser.where(id: skill_user_ids)
    referals = Referal.where(id: referal_ids)

    begin
      Skill.transaction do
        referals.update_all(skill_id: self.id)
        skill_users.update_all(skill_id: self.id)
        to_skills.delete_all
      end
      return true
    rescue Exception => e
      return false
    end  
  end

  def apply_merge(skill_ids_to_merge)
    return false if skill_ids_to_merge.blank?
    return merge!(skill_ids_to_merge)
  end

  def self.import(path = Rails.root.join('lib','data/skills.xlsx'))
     unless path.blank?
      Skill.delete_all
      file =  File.open(path,"r")
      spreadsheet = open_spreadsheet(file)
      header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
          row = Hash[[header.map!(&:downcase), spreadsheet.row(i)].transpose]
          skill = Skill.new
          skill.attributes = row.to_hash.slice(*accessible_attributes)
          skill.save!
        end
        file.close
     end
  end	

  def self.open_spreadsheet(file)
  
    case File.extname(File.basename(file.path))
    #case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.insert_and_return(names)
    return nil if names.blank?
    skills = []
    names.split(/[;:,]/i).map(&:squish).each do |name|
      name = name.try(:downcase).try(:titleize)
      skills << Skill.find_or_create_by_name(name)
    end
    skills
  end

end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < Admin::AdminsController
  before_filter :find_skill , :only => [:edit, :update, :destroy, :force_destroy] 
  before_filter :set_page_params , :only => [:index, :search] 
  #caches_action :index, :expires_in => 12.hours.to_i

  def index
    @skills = Skill.includes(:users).order('name ASC').paginate(:page => @page , :per_page => @per_page)
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(params[:skill])
    if @skill.save
      expire_action :action => 'index'
      redirect_to admin_skills_path, notice: 'Skill has been created successfully'
    else
      render :new
    end
  end

  def search
    @skills = Skill.search do
      fulltext params[:query] || ''
    end.results.paginate(:page => @page , :per_page => @per_page)
  end

  def update
    if @skill.update_attributes(params[:skill])
      redirect_to admin_skills_path(page: (params[:page] || 1)), notice: 'Skill has been updated successfully'
    else
      render :new
    end
  end

  def force_destroy
    ActiveRecord::Base.transaction do
      User.where(id: @skill.users.map(&:id)).destroy_all
      @skill.destroy
    end  

    if @skill.destroyed?
      @res= {success: true, message: "Skill and associated users has been deleted successfully"}
    else
      @res = {success: false, message: "Skill could not be destroyed"}
    end      
  end

  def destroy
    if @skill.users.count == 0
      @skill.destroy
      @res= {success: true, message: "Skill has been destroyed successfully"}
    else
      @res = {success: false, message: "Skill can be destroyed only if users count is zero"}
    end  
  end

  def merge
    @skill = Skill.where(name: params[:with_skill_name]).first
    @skill_ids_to_merge = (params[:to_skill_ids] || "").split(",").map(&:to_i)

    if @skill.blank? || @skill_ids_to_merge.blank? 
      redirect_to new_merge_admin_skills_path({to_skill_ids: params[:to_skill_ids], with_skill_name: params[:with_skill_name]}), alert: 'Skill not found'
    else  
      if @skill.apply_merge(@skill_ids_to_merge)
        redirect_to admin_skills_path, notice: 'Skills have been merged successfully'
      else
        redirect_to new_merge_admin_skills_path({to_skill_ids: params[:to_skill_ids], with_skill_name: params[:with_skill_name]}), alert: 'Skills could not merged'
      end
    end  
  end

  private

  def find_skill
    @skill = Skill.where(id: params[:id]).first
  end

  def set_page_params
    @page = params[:page].try(:to_i) || 1
    @per_page = 50    
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end


  def autocomplete  
    # @skills = Skill.where("lower(name) like ?", "%#{params[:term].downcase}%")
    # render json: @skills

      skill_ids = current_user.skill_ids if !params[:offering].blank?

      if !skill_ids.blank?
        @skills =  Skill.search do
          fulltext params[:term]
          with(:id, skill_ids)
          paginate :page => 1, :per_page => 1000
        end.results
      else
        @skills =  Skill.search do
          fulltext params[:term]
          paginate :page => 1, :per_page => 1000
        end.results
      end  

      render json: @skills
  end

end

app/helpers/admin/skills_helper.rb
module Admin::SkillsHelper

	def serial_number(page, per_page, index)
		(@per_page*(@page - 1)) + (index+1)
	end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/admin/skills/_form.html.erb
<%= form_for [:admin, @skill] do |f| %>

  <%= render :partial => 'shared/error_messages', :locals => {:target => @skill}%>

  <div class='row'>
    <div class='col-md-2'>
      <label>Name:</label>
    </div>
    <div class='col-md-10'>
      <%= hidden_field_tag :page, (params[:page] || 1) %>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <br/>

  <div class='row'>
    <div class='col-md-6 col-md-offset-6'>
      <%= f.submit :submit ,class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/skills/_search.html.erb
<%= form_tag search_admin_skills_path do |f| %>
  <div class='row'>
    <div class='col-md-5'>
      <%= text_field_tag :query, params[:query], :class => 'form-control' %>
    </div>  
    <div class='col-md-2'>
      <%= submit_tag :search, :class => 'btn btn-default' %>
    </div>     
  </div>
<% end %>

app/views/admin/skills/_skills.html.erb
<!-- <div class="users_list digg_pagination">
  <%#= will_paginate @skills, :container => false %>
</div>
 -->
<div class="skills">
  <table width="647" class="table table-striped table-hover">
    <tr>
      <th>Serial </th>
     <!--  <th>State</th> -->
      <th>Name</th>
      <th>Users count</th>
      <th class='action-btns'></th>
    </tr>

    <% @skills.each_with_index do |skill, index| %>
        <tr id="<%= dom_id(skill) %>">
          <td><a href="javascript:void(0)">#<%= serial_number(@page, @per_page, index) %></a></td>
          <td><%= skill.name %></td>
          <td><%= skill.users.count %></td>
          <td class='view_edit'> 
            <span><%= link_to 'Edit', edit_admin_skill_path(skill, {page: params[:page]}), class: 'btn btn-sm btn-primary' %></span>
            <span><%= link_to 'Remove', admin_skill_path(skill), class: 'btn btn-sm btn-danger', remote: true, :data => {:confirm => 'Are you sure?', method: :delete } %></span>
            <span><%= link_to 'Force remove', force_destroy_admin_skill_path(skill), class: 'btn btn-sm btn-danger', remote: true, :data => {:confirm => 'Are you sure?', method: :delete } %></span>            
          </td>    
        </tr>
    <% end %>    
  </table>
</div>

<div class="skills digg_pagination">
  <%= will_paginate @skills, :container => false %>
</div>


<script type="text/javascript">
    $('#skills .digg_pagination a').on('click', function (event) {
      event.preventDefault();
      show_loader();
      $.getScript(this.href)
        .complete(function( script, textStatus ) {
          hide_loader();
        }).error(function (XMLHttpRequest, textStatus, errorThrown) {
            console.log('error ', errorThrown);
            alert('Error: '+errorThrown);
        });
    });
</script>

app/views/admin/skills/destroy.js.erb
<% if @res[:success] %>
  $("#<%= dom_id(@skill)%>").slideUp().remove();
<% else %>
  alert("<%= @res[:message] %>")
<% end %>

app/views/admin/skills/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/skills/force_destroy.js.erb
<% if @res[:success] %>
  $("#<%= dom_id(@skill)%>").slideUp().remove();
<% else %>
  alert("<%= @res[:message] %>")
<% end %>

app/views/admin/skills/index.html.erb
<% content_for :header do %>
  <div class="title_head">
    <div class="container">
      <div class="col-md-4">
        <p class="admin_h">Admin /</p>
        <h2 class="orders_h">Skills</h2>
      </div>
    </div>
  </div>
<% end %>

<div class='row'>
  <div class='col-md-7'>
    <%= render :partial => 'search' %>
  </div>  
  <div class='col-md-1'>
    <%= link_to 'New skill', new_admin_skill_path, :class => 'btn btn-primary' %>
  </div>  
  <div class='col-md-1'>
    <%= link_to 'Merge skills', new_merge_admin_skills_path, :class => 'btn btn-primary' %>
  </div>  
  <div class='col-md-3'>
  </div>      
</div>

<div id='skills'>
  <%= render :partial => 'skills' %>
</div>

app/views/admin/skills/index.js.erb
$('#skills').html('<%= escape_javascript(render("skills")) %>');

$('#skills .digg_pagination a').on('click', function () {
  $.getScript(this.href);
  return false;
});

app/views/admin/skills/new.html.erb
<%= render :partial => 'form' %>

app/views/admin/skills/new_merge.html.erb
<% content_for :header do %>
  <div class="title_head">
    <div class="container">
      <div class="col-md-4">
        <p class="admin_h">Admin /</p>
        <h2 class="orders_h">Merge Skills</h2>
      </div>
    </div>
  </div>
<% end %>

<!-- <div class='row pull-right'>  
  <div class='col-md-6'>
    <%#= link_to 'New skill', new_admin_skill_path, :class => 'btn btn-primary' %>
  </div>  
  <div class='col-md-6'>
    <%#= link_to 'Skills', admin_skills_path, :class => 'btn btn-primary' %>
  </div>  
</div> -->

<div id='merge-skills'>
  
  <%= form_tag merge_admin_skills_path, id: 'skills-merge-form' do %>
    <div class="row">
      <div class='col-md-5'>
        <h4>Select skill to remove</h4>
        <%= text_field_tag :to_skill_ids, params[:to_skill_ids], class: 'form-control', id: "skill-to-remove" %>
      </div>
      <div class='col-md-5'>
        <h4>Select skill to merge with</h4>
        <%= text_field_tag :with_skill_name, params[:with_skill_name], class: 'form-control', id: "skill-with-merge" %>
      </div>
      <div class='col-md-2' style="margin-top: 39px;">
        <%= submit_tag :Merge, class: 'btn btn-primary'%>
      </div>    
    </div>
  <% end %>  

</div>

app/views/admin/skills/search.html.erb
<% content_for :header do %>
  <div class="title_head">
    <div class="container">
      <div class="col-md-4">
        <p class="admin_h">Admin /</p>
        <h2 class="orders_h">Skills</h2>
      </div>
    </div>
  </div>
<% end %>

<div class='row'>
  <div class='col-md-7'>
    <%= render :partial => 'search' %>
  </div>  
  <div class='col-md-5'>
    <%= link_to 'New skill', new_admin_skill_path, :class => 'btn btn-primary' %>
  </div>    
</div>

<div id='skills'>
  <%= render :partial => 'skills' %>
</div>

<script type="text/javascript">
  $('#skills .digg_pagination a').on('click', function () {
    $.getScript(this.href);
    return false;
  });
</script>