config/routes.rb
Riszil::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get '/robots.txt' => 'welcome#robots'
  get 'express_payment' => 'users#express_payment', :as => 'express_payment'
  post 'save_locations' => 'users#save_locations', :as => 'save_locations'

  resources :temp_locations do     
  end

  resources :locations do
    collection do
      post 'temp_import'
      get 'sample_csv'
      post 'process_payment'
      get 'express_checkout'     
      get 'express_payment' 
    end     
  end

  resource :referral_card, only: [:show] do
    post 'print'
  end

  resources :referals do
    collection do
      get 'search' , :action => 'search'
    end 

    member do
      post 'move' , :action => 'move'
      delete 'remove' , :action => 'remove'
    end
  end  

  resource :search , :only => [:none] do
      #post "users" ,:action => 'search'
      get "users" ,:action => 'search'
      get "suggestions" ,:action => 'suggestions'
  end  

  resources :skills do
    collection do
      get 'autocomplete' , :action => 'autocomplete'
    end  
  end  

  resources :barters , :only => [:index] do
    collection do
      get 'search'
    end  
  end  

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]  

  get '/profile/tips' => 'welcome#profile_tips', :as => 'profile_tips'
  #get '/contests_promotions' => 'welcome#contests_promotions', :as => 'contests_promotions'
  # get '/about' => 'welcome#about_us', :as => 'about_us'
  # get '/comming_soon' => 'welcome#comming_soon'
  get '/country/subregion_options' => 'welcome#subregion_options'

  get "schedule/new"

  get "photo/new"

  get "photo/create"

  get "photo/show"

  get "affiliate_programme" => redirect("/") # "welcome#affiliate_programme", :as => 'affiliate_programme'
  
  get "what_is_riszil" =>  "welcome#what_is_riszil", :as => 'what_is_riszil'

  get "passwords/edit" => "passwords#edit", :as => 'edit_password'
  put "passwords/update" => "passwords#update", :as => 'update_password'

  devise_for :users, :controllers => {:registrations => "newregistrations",:sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks"}
  
  resources :users,only:[:none] do
    member do
      post 'edit_referal'
      post 'update_referal'
    end
    resources :photos, :except => [:update, :edit] do
      member do
        post 'set_as_profile_photo' ,:action => 'set_as_profile_photo'
      end  
    end  
    resource :schedule
    member do
      post 'rate' , :action => 'rate'
      get 'report'
      #get "request_pay"
    end  
    collection do
      put 'post_feedback/:business_id' , :action => 'post_feedback' , :as => 'post_feedback'
    end
  end


  get 'membership' => "memberships#index", :as => 'membership'
  get 'membership/plans' => "memberships#new", :as => 'membership_plans'
  get 'membership/change' => "memberships#change", :as => 'change_membership'
  post 'membership/upgrade' => "memberships#upgrade", :as => 'upgrade_membership'
  get 'membership/express_checkout' => "memberships#express_checkout", :as => 'express_checkout_membership'
  get 'membership/process_payment' => "memberships#process_payment", :as => 'process_payment_membership'

  resources :invites, :only => [:new, :create] do
    collection do
      get 'preview'
    end
  end

  get 'invites/decline/:token' => "invites#decline", :as => 'decline_invite'

  resources :zipcodes do
    collection do
      get 'zip'
    end
  end
  
  #resources :affiliates 
  get "w9_form" => "affiliates#w9_form_detail"
  get "affiliate" => "affiliates#affiliate" 
  post "w9_form" => "affiliates#create_w9_form_detail"
  put "w9_form" => "affiliates#update_w9_form_detail" 
  get "contact_us" => "welcome#contact_us"
  post "send_visitor_info" => "welcome#send_visitor_info"

  root :to => "welcome#index"

  get "new_payment_detail" => "welcome#new_payment_detail"

  namespace :admin do
    get '/' => "users#dashboard" , :as => "root"
    get 'users' => "users#index" , :as => "users"
    get 'login' => "admins#login" , :as => "login" 
    get 'reward_transaction' => "admins#reward_transaction" , :as => "reward_transaction" 
              
    resources :email_verification_logs, only: [:index]           
    resources :affiliates
    resources :users do
      collection do
          get 'start_hubuco'
          get 'search',:action => "search" , :as => "search"  
          get 'import'
          get 'claimed'
          get 'recent'
          post 'upload_csv'            
      end        
      member do
          post 'pay_affiliation_reward',:action => "pay_affiliation_reward"
          put 'activate'
          put 'deactivate'
      end  
    end  
    resources :skills do
      collection do
        get 'search'
        post 'search'
        post 'merge'
        get 'new_merge'
      end
      member do
        delete 'force_destroy'
      end 
    end 
    resources :user_imports do
      collection do
        get 'failed'
      end  
      member do
        post 'retry'
      end        
    end     
  end  

  match 'fbhome',to: 'welcome#fbhome', via: [:get]

  # authenticated :user do
  #   get ":username" => "users#show", :as => 'user'
  # end

  # get ":username" => "welcome#index" , :as => 'user'

  get ":username" => "users#show", :as => 'user'

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_filter :authenticate_user! , :except => [:new]

  layout 'register'

  def new
    redirect_to membership_path if current_user
  end

  def change
    if params[:downgrade]
      if current_user.update_membership(params[:membership])
        flash[:notice] = "Membership downgraded successfully"   
      else
        flash[:alert] = current_user.errors.full_messages.join(",")  
      end
    elsif params[:upgrade] && current_user.can_upgrade_role_to?(params[:membership])
      #TODO : Just remove this condition if you want payment for business mebrship too
      if params[:membership] ==  Role::ROLES[:business][:name]
        current_user.update_membership(params[:membership])
      else  
        @payment_detail = current_user.build_payment_detail(:upgrading_to => params[:membership])
      end  
    end 
  end

  def upgrade
    @payment_detail = current_user.build_payment_detail(params[:payment_detail])
    current_user.membership = @payment_detail.upgrading_to
    @res = if current_user.save_with_payment
      {:success => true , :message => "Membership upgraded successfully"}
    else
      {:success => false , :message => "Membership could not be upgraded"}
    end
  end

  # While upgrading to paid plan
  def express_checkout
    redirect_to membership_path, alert: 'You are already a premium member' if current_user.premium_user? 
    redirect_to membership_path, alert: 'Not a valid request to upgrade membership plan' if params[:express_checkout].blank?

    redirect_to EXPRESS_GATEWAY.redirect_url_for(express_checkout_token)
  end

  def process_payment
    #redirect_to membership_path, alert: 'Invalid token' if params[:token].blank?
    # "token"=>"EC-02N40293JF5951930", 
    # "PayerID"=>"PNY8Q686F25LG"

    payment_detail = current_user.build_payment_detail
    payment_detail.express_token = params[:token]    
    current_user.membership = Role::ROLES[:premium][:name]

    if payment_detail.valid? && current_user.save_with_payment
      flash[:notice] = "You have successfully upgraded to #{current_user.membership} membership plan"  
      redirect_to membership_path
    else
      flash[:alert] = "Payment could not be completed"
      redirect_to membership_path
    end
  end


  private

  def express_checkout_token
    response = EXPRESS_GATEWAY.setup_purchase(Role::ROLES[:premium][:price]*100,
      ip: request.remote_ip,
      return_url: process_payment_membership_url,
      cancel_return_url: membership_url,
      currency: "USD",
      allow_guest_checkout: true,
      items: [{name: "Premium signup", description: "Signup as premium user", quantity: "1", amount: Role::ROLES[:premium][:price]*100}]
    )

    return response.token    
  end  

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_payment.html.erb
<div id="paymentModal" class="modal fade" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Upgrade membership payment detail</h4>
      </div>

      <ul class="nav nav-tabs nav-payment-tabs" role="tablist">
        <li class='active'>
          <a href="#credit_card" role="tab" data-toggle="tab" data-payment="credit_card">
            <icon class="fa fa-credit-card"></icon> Credit Card
          </a>
        </li>
        <li>
          <a href="#checkout" role="tab" data-toggle="tab" data-payment="checkout">
             <%= image_tag "paypal-logo.png",  alt: "paypal button" %>
          </a>
        </li>
      </ul>
      
      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane fade active in" id="credit_card">
          <div class="tab-pane-content">
            <%= form_for @payment_detail , :url => upgrade_membership_path , :remote => true do |pd| %>
                <div class="modal-body">
                  <div class=" row">
                    <h3>Card Information</h3>
                    <div class="alert" style="display:none;"></div>
                    <div class="col-sm-12">
                      <div class="inp-m-row col-sm-6 car-inf">
                        <p>Card type </p>
                        <%= pd.hidden_field :upgrading_to %>
                        <%= pd.select :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]] , {},:class=>"form-control"%>
                      </div>
                      <div class="inp-m-row col-sm-6 car-inf-2">
                        <p>Card number </p>
                        <%= pd.text_field :card_number , :class=>"form-control"%>
                      </div>
                      <div class="inp-m-row col-sm-6 car-inf">
                        <p>Card verification value (CVV)  </p>
                        <%= pd.text_field :card_verification , :class=>"form-control" %>
                      </div>
                      <div class="inp-m-row col-sm-6 car-inf-2">
                        <p>Card expires on  </p>
                        <%= pd.date_select :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true, :class =>"select3 list_s1 form-control", :order => [:day, :month, :year], :date_separator => "" %>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                  <button id="new-payment-submit-btn" type="submit" class="btn btn-primary ladda-button" data-style="expand-right"><span class="ladda-label">Pay now</span></button>

                </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="checkout">
          <div class="tab-pane-content">
            <h3>Express checkout</h3>
            <div class="">
              <%= link_to (image_tag "paypal-checkout.gif",  alt: "paypal button"), express_checkout_membership_path(express_checkout: true) %>
            </div>
          </div>  
        </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/memberships/_plans.html.erb
<div class="paln-box">
  <div class="col-sm-4 pln-cll1">
    <div class="plan-in">
      <div class="btn-box"> <a href="#" class="plan-btn-1">Homowner
        service seeker</a> </div>
      <h2>Free</h2>
      <div class="plan-txt">For Searching, Rating & Referring <span>(no skill or conact info listed)</span></div>
      <div class="wth-arrow"></div>
      <div class="plan-btn-box"> 
        <% if current_user.role?('basic') %>
          <a class="btn btn-default btn-plan-select" href="<%= edit_user_registration_path %>">
            <span class="current-plan">Current plan</span>  
          </a>
        <%  else %>  
          <% if current_user.can_upgrade_role_to?('basic')  %>
            <a data-remote="true" href="<%= change_membership_path(:upgrade => true , :membership => :basic) %>" class="btn btn-warning ladda-button btn-plan-select ajax-ladda-loader" data-style="expand-right"><span class="ladda-label">Upgrade</span></a>  
          <% else %>
            <a data-remote="true" data-confirm="WARNING:: you are downgrading your plan. there is no refund for plan change. Are you sure?" href="<%= change_membership_path(:downgrade => true , :membership => :basic) %>" class="btn btn-warning ladda-button btn-plan-select ajax-ladda-loader" data-style="expand-right"><span class="ladda-label">Downgrade</span></a>
          <% end %>
        <% end %>  
      </div>
    </div>
  </div>
  <div class="col-sm-4 pln-cll1">
    <div class="plan-in sec-in">
      <div class="btn-box"> <a href="#" class="plan-btn-1 pl-bt2">Contractor
        Tradesman 
        Professional <span>Or</span></a> </div>
      <h2>Free</h2>
      <div class="plan-txt">For searching, Rating & Referring 
        but Can list only one skills and will
        have contact info listed.
      </div>
      <div class="wth-arrow"></div>
      <div class="plan-btn-box">
        <% if current_user.role?('business') %>
          <a class="btn btn-default btn-plan-select" href="<%= edit_user_registration_path %>">
            <span class="current-plan">Current plan</span>  
          </a>
        <%  else %>  
            <% if current_user.can_upgrade_role_to?('business')  %>
              <a data-remote="true" href="<%= change_membership_path(:upgrade => true , :membership => :business) %>" class="btn btn-warning ladda-button btn-plan-select ajax-ladda-loader" data-style="expand-right"><span class="ladda-label">Upgrade</span></a>  
            <% else %>
              <a data-remote="true" data-confirm="WARNING:: you are downgrading your plan. there is no refund for plan change. Are you sure?" href="<%= change_membership_path(:downgrade => true , :membership => :business) %>" class="btn btn-warning ladda-button btn-plan-select ajax-ladda-loader" data-style="expand-right"><span class="ladda-label">Downgrade</span></a>
            <% end %>
        <% end %>  
      </div>
    </div>
  </div>
  <div class="col-sm-4 pln-cll1">
    <div class="plan-in three-in">
      <div class="btn-box"> <a href="#" class="plan-btn-1 pl-bt3">Premium</a> </div>
      <div class="rec"><a href="#">Recommened</a></div>
      <div class="yer-txt"><span>$50</span> Yearly Subscription</div>
      
      <div class="plan-txt">For searching, Rating & Referring 
        Can list unlimited skills and will
        have contact info listed.
      </div>
      <div class="wth-arrow"></div>
      <div class="plan-btn-box"> 

        <% if current_user.role?('premium') %>
          <a class="btn btn-default btn-plan-select" href="<%= edit_user_registration_path %>">
            <span class="current-plan">Current plan</span>  
          </a>
        <%  else %>  
            <% if current_user.can_upgrade_role_to?('premium')  %>
              <a data-remote="true" href="<%= change_membership_path(:upgrade => true , :membership => :premium) %>" class="btn btn-warning ladda-button btn-plan-select ajax-ladda-loader" data-style="expand-right"><span class="ladda-label">Upgrade</span></a>  
            <% else %>
              <a data-remote="true" data-confirm="WARNING:: you are downgrading your plan. there is no refund for plan change. Are you sure?" href="<%= change_membership_path(:downgrade => true , :membership => :premium) %>" class="btn btn-warning ladda-button btn-plan-select ajax-ladda-loader" data-style="expand-right"><span class="ladda-label">Downgrade</span></a>
            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/memberships/change.js.erb
<% if @payment_detail %>
  
    var paymentModal = '';

    if ($("#paymentModal").length){
      paymentModal = $("#paymentModal");
    }else{
      paymentModal = $("<%=escape_javascript(render :partial=>'payment' )%>");
    }
    
    paymentModal.modal();
    paymentModal.on('hidden.bs.modal', function () {
      $('.modal-backdrop').remove();
    });

    paymentModal.on('shown.bs.modal', function () {
        $("#new_payment_detail").bind("ajax:beforeSend", function (e, data, status, xhr){
          var l = Ladda.create($(this).find("#new-payment-submit-btn").get(0));
          l.start();    
        }).bind("ajax:complete", function (e, data, status, xhr){
          var l = Ladda.create($(this).find("#new-payment-submit-btn").get(0));
          l.stop();    
        })
    });

<% else %>
  $("#flash-message").html("<%= escape_javascript(render('/shared/flash_messages')) %>");
  $("#flash-message").slideDown();
  <% if current_user.errors.empty?  %>
    $("#membership-plans").html("<%= escape_javascript(render('plans')) %>");
  <% end %> 
<% end %>

apply_ladda_loader();

app/views/memberships/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "pricing" %>
<% end %> 

<div id="membership-plans">
  <%= render :partial => "plans"%>
</div>

app/views/memberships/new.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "pricing" %>
<% end %> 

<div id="membership-plans">
 <%= render :partial => "devise/registrations/plans"%>
</div>

app/views/memberships/upgrade.js.erb
<% if @res[:success] %>
  $("#new_payment_detail")
    .find(".alert")
    .removeClass("alert-danger")
    .addClass("alert-success")
    .html("<%= @res[:message] %>")
    .slideDown();

    paymentModal = $("#paymentModal");
    paymentModal.modal();
    paymentModal.on('hidden.bs.modal', function () {
      window.location.href = "/membership";
    });

<% else %>
  $("#new_payment_detail")
    .find(".alert")
    .removeClass("alert-success")
    .addClass("alert-danger")
    .html("<%= @res[:message] %>")
    .slideDown();
<% end %>