config/routes.rb
Riszil::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get '/robots.txt' => 'welcome#robots'
  get 'express_payment' => 'users#express_payment', :as => 'express_payment'
  post 'save_locations' => 'users#save_locations', :as => 'save_locations'

  resources :temp_locations do     
  end

  resources :locations do
    collection do
      post 'temp_import'
      get 'sample_csv'
      post 'process_payment'
      get 'express_checkout'     
      get 'express_payment' 
    end     
  end

  resource :referral_card, only: [:show] do
    post 'print'
  end

  resources :referals do
    collection do
      get 'search' , :action => 'search'
    end 

    member do
      post 'move' , :action => 'move'
      delete 'remove' , :action => 'remove'
    end
  end  

  resource :search , :only => [:none] do
      #post "users" ,:action => 'search'
      get "users" ,:action => 'search'
      get "suggestions" ,:action => 'suggestions'
  end  

  resources :skills do
    collection do
      get 'autocomplete' , :action => 'autocomplete'
    end  
  end  

  resources :barters , :only => [:index] do
    collection do
      get 'search'
    end  
  end  

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]  

  get '/profile/tips' => 'welcome#profile_tips', :as => 'profile_tips'
  #get '/contests_promotions' => 'welcome#contests_promotions', :as => 'contests_promotions'
  # get '/about' => 'welcome#about_us', :as => 'about_us'
  # get '/comming_soon' => 'welcome#comming_soon'
  get '/country/subregion_options' => 'welcome#subregion_options'

  get "schedule/new"

  get "photo/new"

  get "photo/create"

  get "photo/show"

  get "affiliate_programme" => redirect("/") # "welcome#affiliate_programme", :as => 'affiliate_programme'
  
  get "what_is_riszil" =>  "welcome#what_is_riszil", :as => 'what_is_riszil'

  get "passwords/edit" => "passwords#edit", :as => 'edit_password'
  put "passwords/update" => "passwords#update", :as => 'update_password'

  devise_for :users, :controllers => {:registrations => "newregistrations",:sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks"}
  
  resources :users,only:[:none] do
    member do
      post 'edit_referal'
      post 'update_referal'
    end
    resources :photos, :except => [:update, :edit] do
      member do
        post 'set_as_profile_photo' ,:action => 'set_as_profile_photo'
      end  
    end  
    resource :schedule
    member do
      post 'rate' , :action => 'rate'
      get 'report'
      #get "request_pay"
    end  
    collection do
      put 'post_feedback/:business_id' , :action => 'post_feedback' , :as => 'post_feedback'
    end
  end


  get 'membership' => "memberships#index", :as => 'membership'
  get 'membership/plans' => "memberships#new", :as => 'membership_plans'
  get 'membership/change' => "memberships#change", :as => 'change_membership'
  post 'membership/upgrade' => "memberships#upgrade", :as => 'upgrade_membership'
  get 'membership/express_checkout' => "memberships#express_checkout", :as => 'express_checkout_membership'
  get 'membership/process_payment' => "memberships#process_payment", :as => 'process_payment_membership'

  resources :invites, :only => [:new, :create] do
    collection do
      get 'preview'
    end
  end

  get 'invites/decline/:token' => "invites#decline", :as => 'decline_invite'

  resources :zipcodes do
    collection do
      get 'zip'
    end
  end
  
  #resources :affiliates 
  get "w9_form" => "affiliates#w9_form_detail"
  get "affiliate" => "affiliates#affiliate" 
  post "w9_form" => "affiliates#create_w9_form_detail"
  put "w9_form" => "affiliates#update_w9_form_detail" 
  get "contact_us" => "welcome#contact_us"
  post "send_visitor_info" => "welcome#send_visitor_info"

  root :to => "welcome#index"

  get "new_payment_detail" => "welcome#new_payment_detail"

  namespace :admin do
    get '/' => "users#dashboard" , :as => "root"
    get 'users' => "users#index" , :as => "users"
    get 'login' => "admins#login" , :as => "login" 
    get 'reward_transaction' => "admins#reward_transaction" , :as => "reward_transaction" 
              
    resources :email_verification_logs, only: [:index]           
    resources :affiliates
    resources :users do
      collection do
          get 'start_hubuco'
          get 'search',:action => "search" , :as => "search"  
          get 'import'
          get 'claimed'
          get 'recent'
          post 'upload_csv'            
      end        
      member do
          post 'pay_affiliation_reward',:action => "pay_affiliation_reward"
          put 'activate'
          put 'deactivate'
      end  
    end  
    resources :skills do
      collection do
        get 'search'
        post 'search'
        post 'merge'
        get 'new_merge'
      end
      member do
        delete 'force_destroy'
      end 
    end 
    resources :user_imports do
      collection do
        get 'failed'
      end  
      member do
        post 'retry'
      end        
    end     
  end  

  match 'fbhome',to: 'welcome#fbhome', via: [:get]

  # authenticated :user do
  #   get ":username" => "users#show", :as => 'user'
  # end

  # get ":username" => "welcome#index" , :as => 'user'

  get ":username" => "users#show", :as => 'user'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  RADIUS = 25
  
  skip_before_filter :w9_form_info_for_affiliate, :only => :subregion_options

  def robots                                                                                                                                      
    robots = File.read(Rails.root + "config/robots.#{Rails.env}.txt")
    render :text => robots, :layout => false, :content_type => "text/plain"
  end

  def fbhome
    Rails.logger.info "Params from fb---#{params.inspect}"
    redirect_to root_url, notice: 'Tab has been added to your facebook page successfully'
  end  

  def about_us
  end  

  def index
    if !params[:username].blank?
      @user = User.find_by_username(params[:username])
      referals = @user.referals.includes([:skill]).order("referals.position ASC").limit(10)  
      @referred_skill_names = referals.map {|referal| referal.skill.name}
      flash[:alert] = "Please login or signup before continuing"
    end  

    if !current_user.blank? || !params[:zipcode].blank?
      @from_signup = true  if user_signed_in? && params[:from_signup]
      render :index
    else
      render :what_is_riszil
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def new_payment_detail
    render :partial => 'devise/registrations/payment_detail' ,:locals => {:payment_detail => PaymentDetail.new} ,  :layout => false and return 
  end

  def affiliate_programme
  end	


  def contact_us
  end 

  def send_visitor_info

    if verify_aritcaptcha(params)
        contact_us = {}
        contact_us[:email] =  params[:email]
        contact_us[:subject] =  params[:subject]
        contact_us[:message] =  params[:message]
        UserMailer.send_visitor_info(contact_us).deliver
        flash[:notice] = "You have submitted the message successfully."
        redirect_to root_path
    else
        flash[:alert] = "Your answer for equation was incorrect"
        redirect_to :back
    end    
  end 

  def subregion_options
      @target = params[:target]
      render :partial => 'shared/subregion_select' , :layout => false
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about_us.html.erb
<h2 class="heading">About the founding of Riszil</h2>

<p>I am George Gilgen, I have spent over 30 years (25 of them being self employed) in the trades, mostly doing hardwood flooring and general contracting work.</p>

<p>I know how hard it is to find jobs, to advertise your business without braking the bank. There was a two things that always bothered me.</p>

<p>First, AAA widgets was always on the top of the list
Second, There was only the information that the business wanted you to know and see.</p>

<p>Some things I realized along the way was that the referral was the very best way to get a job, and when things are slow, sometimes bartering is a great way to get things done without spending the precious financial reserves.</p>

<h2 class="heading">Then came the Blessing from Heaven</h2>

<p>One morning (in 2012) I woke up with this idea pounding in my head to creating an online business listing that could be very cost effective. One that would not list businesses from A-Z but would list businesses based on feedback ratings, proximity to your home base, and by the length of time as a subscriber. It would actually be a little more of an interactive site, where customers are telling us about the business (good & bad) with the ability to leave feedback for the business and the job they received.</p>

<p>One great idea that came from the database engineer, we call it the Preferred Referral. Where instead of creating a network of people like face book where you can have a 100,000 followers and never have talked to any of them. This is a referral of who I would use in my own home. Where you can pick one business from a skill set i.e., one Electrician, one Plumber, one concrete worker. That way when you do that great job for a customer, they might say I wonder if they know an electrician that does great work like they did. Helping to refer or be referred without have to take time out of your busy schedule.</p>
<p>The barter component is not just check box that says to everyone, I want to barter. This is a little more exact. It is more of I have hardwood flooring skills, I need a new roof, not a hanging macrame plant holder or 35 golf lessons, a roof and only a roof. We have it where you check a box for the service or services you need and only the people offering that service can see that you want to trade.</p>  

</br>


<p>Thank you for visiting,</br>
George Gilgen
</p>

</br>

If you have questions, comments, or concerns please <%= link_to "contact us" , contact_us_path%>

app/views/welcome/affiliate_programme.html.erb
<h2>Sign up and start earning money right away!</h2>

<p>It’s simple to get started with the affiliate program.</p>


<ul style="list-style-type: decimal;">
	<li>
		<%= link_to "Create an account" , new_user_registration_path , :target => "_blank"%>  and accept the option "Do you want to join affiliate program ?"
	</li>
	<li>
		Sale, Sale and Sale.
	</li>
	<li>
		Complete your W9 form detail.
	</li>
	<li>
		Request to get paid. (must be over $100.00)
	</li>
</ul>


<h2>Affiliate FAQs</h2>


<ul>
	<li>
		<p><b>Is there a minimum affiliate payout?</b></br>
		Yes, you get paid for every Referral / Sale you make but you must accumulate $100.00 to request a payout.</p>
	</li>
	<li>
		<p><b>How much do I get paid?</b></br>
		You will be rewarded 40% of every Referral / Sale that you make ($20 for the Business plan and $40 for the Premium plan). With a 10% residual that will be paid out as long as the Referral account is active </p>
	</li>
	<li>
		<p><b>How often do you payout?</b></br>
		Payments are sent out every Friday, request must be received by Thursday 12:00 noon MST.</p>
	</li>
	<li>
		<p><b>How often can I request Money?</b></br>
		You can request money as often as you would like. Payouts are only once a week. So if you make three request in a week, all before Thursday, all three payouts will be combined into one payout on Friday.</p>
	</li>
	<li>
		<p><b>Is there a service charge with the payout?</b></br>
		There is one free payout a month. Any additional payouts will be charged a $3.00 processing fee per payout. (The one exception is if the payouts exceed $10,000.00 there will be no processing fee.)</p>
	</li>
	<li>
		<p><b>How do you payout?</b></br>
		All payment are made through PayPal's Mass Pay (with Mass Pay you don't have the PayPal fees to receive your money.)</p>
	</li>
	<li>
		<p><b>Do I need a PayPal account?</b></br>
		Yes, all payments will be made through PayPal.</p>
	</li>
	<li>
		<p><b>Is there a limit on the number of Referral/Sales I can do?</b></br>
		No, the sky is the limit.</p>
	</li>
	<li>
		<p><b>Are taxes taken out of my pay?</b></br>
		No, you will be classified as an independent contractor and you will be responsible for your own taxes.</p>
	</li>

	<li>
		<p><b>Will I get a 1099 tax form at the end of the year?</b></br>
		Yes, if you requested money you will get a 1099 tax form.</p>
	</li>

	<li>
		<p><b>How are the Referral/Sales tracked?</b></br>
		At the top of the sign up page is a referrer email box. Your email that you signed up with, must go in that box to get credit.</p>
	</li>


	<li>
		<p><b>Can I set up my own sales force? </b></br>
		Yes, for every salesperson you are helping you will be rewarded 20% of their referral/sales and a 5% residual.</p>
	</li>
	<li>
		<p><b>Do I have to be a paying customer to do affiliate sales for Riszil?</b></br>
		No, but if you choose to be a non-subscribing affiliate sales person, you will need to make one referral/sale a month to stay active.</p>
	</li>
	<li>
		<p><b>What happens if I go inactive?</b></br>
		Inactive affiliate will get no credit for their sales teams referral/sales or their personal and sales teams residuals, that sign up or renew during your inactive period.</p>
	</li>
	<li>
		<p><b>What if I lie, cheat, and/or mislead businesses into signing up?</b></br>
		Your account will be disabled and you will forfeit all current and future rewards.</p>
	</li>
</ul>

app/views/welcome/comming_soon.html.erb
<h1 class="comming_soon">
  Comming Soon!
</h1>

app/views/welcome/contact_us.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "contact_us" %>
  <%= stylesheet_link_tag "validationEngine.jquery" %>
  <%= javascript_include_tag "jquery.validationEngine" %>  
  <%= javascript_include_tag "jquery.validationEngine-es" %>  
<% end %>


<div class="contact_box">
              <p class="text_aflt">Contact Us</p>
  <div class="contact_boxLeft">
		
    <%= form_tag   send_visitor_info_path , :id => "contact-us" do %>
                  <div>Email </div>
                    <%= text_field_tag :email , '',:class => "validate[required,custom[email]]" %>
                  <div>Subject </div>
                    <%= text_field_tag :subject , '',:class => "validate[required]"%>
                  <div>Message </div>
                  <%= text_area_tag :message , '',:cols=>"45" , :rows=>"5" , :id => "textarea", :class => "validate[required]" %>

                  <div>Please solve this simple equation </div>
            <div>
                  
                    <div class="captcha_box">
                      <%= raw aritcaptcha_tag :operations => [:add, :sub] %>
                    </div>
                    
                    <div class="login_btn_r">
          		        <input type="submit" name="Submit" value="SUBMIT" class="btn_r1">
          		      </div>

                </div>
          <% end %>
  </div>
    
    <div class="clear"></div>
</div>


<script type="text/javascript">
  $("#contact-us").validationEngine();
</script>

app/views/welcome/contests_promotions.html.erb
<h2><%= link_to "Invite a Friend", new_invite_path%></h2>
<h2> Join &amp; Referral Contest</h2>
<ul>
  <li>
    <p><strong>Who can enter?<br />
      </strong>Any "Homeowner / Service Seeker", "Contractor, Tradesmen or Professional", that join as a free member or the premium listing. must be 18 or older, living in the USA.</p>
  </li>
  <li>
    <p><strong>When and how will the winner be selected?<br />
      </strong>After we hit the mark of 4,000 new sign ups from the start of the contest. We will randomly select 10 Profile pages, these will be the semi-finalist. from their we will verify the legitimacy of the page (e-mail, address and phone number). Any that can not be verified will be disqualified. From the remaining  semi-finalist we will put the names of the person that signed up and the person that refered them in a hat and draw the winner( if a Premium subscriber and referee make it to the semi-finials there names will be entered twice). <strong></strong></p>
  </li>
  <li>
    <p><strong>Things you must do to qualified?<br />
      </strong>Must be at least 18 years of age. Must reside in the USA. Must have valid contact info. Must have a Profile Picture. If a Business, must have at least basic info in the "About My Company" section of the profile page and be willing to have your name published.</p>
  </li>
  <li>
    <p><strong>How will I know if I will?<br />
      </strong>You will be contacted by phone and e-mail to verify contact info, if you make it to the semi-finals and by phone if you win. </p>
  </li>
  <li>
    <p>
      <strong>How will I get payed?<br />
      </strong>The payout will be made via PayPal MassPay only after receiving a completed W-9 form for tax purposes.
    </p>
    <h2><%= link_to "Invite a Friend", new_invite_path %></h2>
  </li>
</ul>

app/views/welcome/index.html.erb
<% content_for :footer do %>
  <% if @from_signup %>
      <!-- modal -->
      <div id="completeProfileModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h5 class="modal-title">Would you like finish your Business profile now ?</h5>
            </div>
            <div class="modal-body">
              <div style="padding:20px;text-align: center;">
                <%= link_to "Yes", edit_user_registration_path, :class => "btn btn-success btn-lg"%>
                <button type="button" class="btn btn-danger btn-lg" data-dismiss="modal">No</button>
              </div>  
            </div>
          </div>

        </div>
      </div>

      <script type="text/javascript">
        $(document).ready(function(){   
          $("#completeProfileModal").modal();
        }); 
      </script>
  <% end %>
<% end %>

<div class="search-form">
<!-- Seach Form Begins -->
<%= form_tag users_search_path, :method =>'get', html: { autocomplete: 'off' }, :id => "welcome_search" do %>

  <div class="row-fluid">
    <div class="search-box span12">
      
      <div class="search-bar">
        <div class="search-input">
          <span class="text">
          
            <% if !params[:zipcode].blank? %>
              <%= hidden_field_tag :zipcode , params[:zipcode]  %>
            <% end %>
            
            <%= text_field_tag :search, params[:search] || "Search here..." ,class: "span12 search_input" ,:id=>"autocomplete-ajax" , :onblur=>"if (this.value == '') {this.value = 'Search here...';}",:onfocus=>"if (this.value == 'Search here...') {this.value = '';}" %>
          </span>
          <span class="search-btn">
            <input type="submit" name="" value="" />
          </span>
        </div>
      </div>
      <h1>SEARCH RESULTS FOR &ldquo;<span id='search-keyword'></span>&rdquo;</h1> 	
    </div>
  </div> 
<% end %>
<!-- Seach Form End -->

<!-- Add Section begin -->
<!-- <div class="row-fluid">
    <div class="fea-frame">
      <ul class="fea-list">

      <li class="span4">
        <div id="barters-tab" class="tabs clickable" data-location="affiliate_programme">
          <h2 class="heading">
            <span class="img">
              <%#= image_tag("mony.png", :alt =>"dollar") %>
            </span><span class="text">earn money</span>
          </h2>
          <p>Get a free membership or earn money selling for Riszil</p>
          <span class="read-more">
            <%#= link_to "Read More...", affiliate_programme_path %>
          </span>
        </div>
      </li>

      <li class="span4 middle_span" >
        <div id="barters-tab" class="tabs clickable" data-location="/barters">
          <h2 class="heading">
          <span class="img">
           <%#= image_tag("skills.png", :alt =>"skills") %>
          </span><span class="text">BARTER SKILLS</span>
          </h2>
          <p>Find people to barter and trade labor with</p>
        </div>
      </li>

      <li class="span4">
        <div id="barters-tab" class="tabs clickable" data-location="/users/sign_up">
          <h2 class="heading">
            <span class="img">
             <%#= image_tag("register.png", :alt =>"user") %>
            </span>
            <span class="text">REGISTER</span>
          </h2>
          <p>Browse and list your skills quickly and easily</p>
           <span class="read-more">
            <%#= link_to "GET STARTED FOR FREE", new_user_registration_path %>
          </span>
        </div>
      </li>

      </ul>
    </div>
</div>  -->

  <div id="users" class="search-result">
    <div class='search search-left'>
      <h4>SERVICE PROVIDER</h4> 
      <div class="row-fluid search_listbox" id='service-providers'>
        <%= render :partial => 'shared/service_providers' if @users %>
      </div>
    </div>  

    <div class='search search-right'>
      <h4>PREFERRED REFERRALS NEAR YOU</h4> 
      <div class="row-fluid search_listbox" id='preferred-referals'>
        <%= render :partial => 'shared/preferred_referals' if @referrals %>
      </div>
    </div>  
  </div>

</div>
<!-- Add Section end -->

app/views/welcome/profile_tips.html.erb
<h2> Profile Page Tips </h2>

<ul>
	<li>
		<p><strong>What is &quot;Preferred  Referrals&quot;?<br />
	    </strong>Preferred Referrals is an elite list of skilled individuals that you would have  working in your home. Most people know that the best customers are the  referrals. This can be a powerful tool for you, if you can't find your guy in  search,  call him get him signed up. Then  let your customers know if you like my work look at my preferred referrals list  in Riszil.</p>
</li>
	<li>
		<p><strong>&quot;About My  Company&quot; should only be as long as it needs to be<br />
	    </strong>Writing for the web is different from writing for print. People skim  online, especially when they first get to a page. You want the contents of your  page to give them what they want quickly, but provide enough detail for those  who want expansion on the basics. If it looks like it needs more add a picture  or two. If you are unfamiliar with the text editor don't forget the ? for help.<strong></strong></p>
</li>
	<li>
		<p><strong>You should think  local and write global<br />
	    </strong>You should make sure that things like currencies, measurements, dates, and  times are clear so that all your readers will know exactly what you mean. </p>
</li>
	<li>
		<p><strong>You should spell  everything correctly<br />
	    </strong>Many people are not tolerant of spelling errors. You can write a completely  error free topic for years, and then have one simple &quot;teh&quot; instead of  &quot;the&quot; and you will get irate e-mails from customers, and many  will give up in disgust without contacting you at all. It may seem unfair, but  people judge profiles by the quality of the writing, spelling, and grammar errors are an obvious indicator of quality for many people.</p>
</li>
	<li>
		<p><strong>Your pages should  have the best and currant contact information<br />
	    </strong>Have contact information that gets to you, not a voice mail or an e-mail account you never use.</p>
	</li>
	</ul>

app/views/welcome/what_is_riszil.html.erb
<div class="row-fluid">
  <div class="fea-frame">
    <div class="span6 mn-left">
      <div class="welcome-txt">
        <h1> Welcome to <span>Riszil</span></h1>
        <p>A new and easy way to find the professional you are looking for</p>
      </div>
      <div class="banner-img"> 
        <%= image_tag "banner-img-home.png" ,:alt=>"img" %>
        <%#= link_to image_tag("join_or_refer.png",:alt=>"Join or Refer"), '#' %>
      </div>
    </div>
    <div class="span6 mn-right">
      <h3>FEATURES</h3>
      <ul>
        <li> <span>Free to Search</span> and <span>Free to List</span></li>
        <li>
          When searching with <span>Riszil.com</span>, you can also see who your friends and neighbors mechanic is, this is much better than just searching and reading reviews to find a mechanic

        </li>
          <li>Search the preferred network of <span>Contractors, Professionals and tradesmen</span>
        </li>


        <li>

          View each service provider’s background, <span>ratings and feedback </span> so you can better decide on which one is best suited for your needs
        </li>


        <li>If you have a professional service provider that you like, 
        add them via <span>Preferred Referral Section.</span></li>
      </ul>

      <div class="know-txt">Can't find the professional service provider that you love to work with? Tell them about<%= link_to image_tag("small-logo.png") ,"javascript:void(0)" %>    
      
      </div>
      <div class="at-txt"> At <span>Riszil</span>, we make it easy for you. </div>
      <div class="rc-row">
      
        <% if current_user.blank? %>
          <button type="button" class="src-btn" data-toggle="modal" data-target="#myModal">Search Without Joining</button>
                  
          <%= link_to "JOIN NOW",membership_plans_path,:class=>"register-btn blue"%>
        <% end %>

      </div>
    </div>
  </div>
</div>



<% content_for :footer do %>
  <!-- modal -->
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h5 class="modal-title">Enter your zipcode to search near by professionals</h5>
        </div>
        <div class="modal-body">
          <%= form_tag root_path, :method => :get do %>
            
            <div class="inp-m-row">
              <span class="ip-txt"> 
                <%= text_field_tag :zipcode , nil%>
              </span>
              <%= submit_tag "submit", :class => "btn btn-default"%>
            </div>

          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
<% end %>