config/routes.rb
Riszil::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get '/robots.txt' => 'welcome#robots'
  get 'express_payment' => 'users#express_payment', :as => 'express_payment'
  post 'save_locations' => 'users#save_locations', :as => 'save_locations'

  resources :temp_locations do     
  end

  resources :locations do
    collection do
      post 'temp_import'
      get 'sample_csv'
      post 'process_payment'
      get 'express_checkout'     
      get 'express_payment' 
    end     
  end

  resource :referral_card, only: [:show] do
    post 'print'
  end

  resources :referals do
    collection do
      get 'search' , :action => 'search'
    end 

    member do
      post 'move' , :action => 'move'
      delete 'remove' , :action => 'remove'
    end
  end  

  resource :search , :only => [:none] do
      #post "users" ,:action => 'search'
      get "users" ,:action => 'search'
      get "suggestions" ,:action => 'suggestions'
  end  

  resources :skills do
    collection do
      get 'autocomplete' , :action => 'autocomplete'
    end  
  end  

  resources :barters , :only => [:index] do
    collection do
      get 'search'
    end  
  end  

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]  

  get '/profile/tips' => 'welcome#profile_tips', :as => 'profile_tips'
  #get '/contests_promotions' => 'welcome#contests_promotions', :as => 'contests_promotions'
  # get '/about' => 'welcome#about_us', :as => 'about_us'
  # get '/comming_soon' => 'welcome#comming_soon'
  get '/country/subregion_options' => 'welcome#subregion_options'

  get "schedule/new"

  get "photo/new"

  get "photo/create"

  get "photo/show"

  get "affiliate_programme" => redirect("/") # "welcome#affiliate_programme", :as => 'affiliate_programme'
  
  get "what_is_riszil" =>  "welcome#what_is_riszil", :as => 'what_is_riszil'

  get "passwords/edit" => "passwords#edit", :as => 'edit_password'
  put "passwords/update" => "passwords#update", :as => 'update_password'

  devise_for :users, :controllers => {:registrations => "newregistrations",:sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks"}
  
  resources :users,only:[:none] do
    member do
      post 'edit_referal'
      post 'update_referal'
    end
    resources :photos, :except => [:update, :edit] do
      member do
        post 'set_as_profile_photo' ,:action => 'set_as_profile_photo'
      end  
    end  
    resource :schedule
    member do
      post 'rate' , :action => 'rate'
      get 'report'
      #get "request_pay"
    end  
    collection do
      put 'post_feedback/:business_id' , :action => 'post_feedback' , :as => 'post_feedback'
    end
  end


  get 'membership' => "memberships#index", :as => 'membership'
  get 'membership/plans' => "memberships#new", :as => 'membership_plans'
  get 'membership/change' => "memberships#change", :as => 'change_membership'
  post 'membership/upgrade' => "memberships#upgrade", :as => 'upgrade_membership'
  get 'membership/express_checkout' => "memberships#express_checkout", :as => 'express_checkout_membership'
  get 'membership/process_payment' => "memberships#process_payment", :as => 'process_payment_membership'

  resources :invites, :only => [:new, :create] do
    collection do
      get 'preview'
    end
  end

  get 'invites/decline/:token' => "invites#decline", :as => 'decline_invite'

  resources :zipcodes do
    collection do
      get 'zip'
    end
  end
  
  #resources :affiliates 
  get "w9_form" => "affiliates#w9_form_detail"
  get "affiliate" => "affiliates#affiliate" 
  post "w9_form" => "affiliates#create_w9_form_detail"
  put "w9_form" => "affiliates#update_w9_form_detail" 
  get "contact_us" => "welcome#contact_us"
  post "send_visitor_info" => "welcome#send_visitor_info"

  root :to => "welcome#index"

  get "new_payment_detail" => "welcome#new_payment_detail"

  namespace :admin do
    get '/' => "users#dashboard" , :as => "root"
    get 'users' => "users#index" , :as => "users"
    get 'login' => "admins#login" , :as => "login" 
    get 'reward_transaction' => "admins#reward_transaction" , :as => "reward_transaction" 
              
    resources :email_verification_logs, only: [:index]           
    resources :affiliates
    resources :users do
      collection do
          get 'start_hubuco'
          get 'search',:action => "search" , :as => "search"  
          get 'import'
          get 'claimed'
          get 'recent'
          post 'upload_csv'            
      end        
      member do
          post 'pay_affiliation_reward',:action => "pay_affiliation_reward"
          put 'activate'
          put 'deactivate'
      end  
    end  
    resources :skills do
      collection do
        get 'search'
        post 'search'
        post 'merge'
        get 'new_merge'
      end
      member do
        delete 'force_destroy'
      end 
    end 
    resources :user_imports do
      collection do
        get 'failed'
      end  
      member do
        post 'retry'
      end        
    end     
  end  

  match 'fbhome',to: 'welcome#fbhome', via: [:get]

  # authenticated :user do
  #   get ":username" => "users#show", :as => 'user'
  # end

  # get ":username" => "welcome#index" , :as => 'user'

  get ":username" => "users#show", :as => 'user'

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController
  
  require 'will_paginate/array'

  before_filter :find_user , :only => [:destroy, :deactivate, :activate, :show, :edit, :update, :pay_affiliation_reward]
  before_filter :check_eligibilty_for_affiliation_reward , :only => [:pay_affiliation_reward]
  before_filter :check_hubuco_script_status, only: [:index, :dashboard]

  caches_action :dashboard, :expires_in => 12.hours.to_i

  def recent
    @days = (params[:days] || '').to_i
    @days = 7 if @days == 0
    @users =  User.not_admin.created_in_last(@days).order('created_at ASC').paginate(:page => params[:page] || 1 , :per_page => 10) || []
  end

  def claimed
    @claimed_users = User.not_admin.claimed
  end  

  def dashboard
    users = User.not_admin
    @failed_user_imports_count = FailedUserImport.count

    @all_users_count = users.count
    @claimed_pages_count = users.claimed.count
    @basic_users_count =  users.basic.count
    @business_users_count = users.business.count  
    @premium_users_count = users.premium.count

    @created_in_last_24_hours = users.created_in_last(1).count
    @created_in_last_7_days = users.created_in_last(7).count
    @created_in_last_30_days = users.created_in_last(30).count

    render layout: 'new_admin'
  end

  def index
    @users = User.not_admin.includes(:role).order('created_at ASC').paginate(:page => params[:page] || 1 , :per_page => 10) || []
  end

  def show 
    @downline_members = @user.downline_members.paginate(:page => params[:page] || 1 , :per_page => 10) || []
  end

  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
      params[:user].delete(:current_password)
    end

    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, :notice => "User updated successfully"
    else
      render :edit
    end
  end

  def activate
    @index = params[:index].try(:to_i)
    @user.activate!
  end

  def deactivate
    @index = params[:index].try(:to_i)
    @user.deactivate!
  end

  def destroy
    @user.destroy!
    @users = User.not_admin.find(:all , :order => "created_at ASC",:include=> :role).paginate(:page => params[:page] || 1 , :per_page => 10) || []
  end

  def search
    @users = if !params[:query].blank? || !params[:role_name].blank?    
          User.search(:include => [:role])do
                fulltext params[:query]
                with :role_name,params[:role_name] if !params[:role_name].blank? 
                paginate :page => params[:page] || 1 , :per_page => 10
              end.results
         else
          User.find(:all , :include=> :role).paginate(:page => params[:page] || 1 , :per_page => 10) || []
         end  
  end

  def pay_affiliation_reward
    if @user.varify_paypal_email
      if @user.payment_using_paypal
        @user.affiliations.update_all( is_rewarded_for: true )
        @user.update_attribute(:is_request_reward, false)
        redirect_to :back , :notice => "Affiliation Reward successfully completed"
      else
         redirect_to :back , :alert => @user.errors.full_messages.join(",")
      end 
    else
      redirect_to :back , :alert => @user.errors.full_messages.join(",")
    end
  end

  def upload_csv
    user_import = UserImport.new(csv: params[:csv])
    if user_import.save
      redirect_to admin_users_path, notice: 'User import job has been started in back ground'
    else
      redirect_to import_admin_users_path, alert: 'Can not be uploaded'
    end  
  end  

  def start_hubuco
   StartHubucoScript.new.run unless hubuco_script_running?
   redirect_to admin_users_path, notice: 'Email verification job has been started successfully'
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def check_eligibilty_for_affiliation_reward
    redirect_to root_path ,:alert => "Reward amount for this affiliate is zero" unless @user.is_reward_amount_more_than_zero? 
  end 
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def total_reward_for_basic_users(tier = :first_tier)
    return @user.total_reward_for_basic_users(tier)
  end 

  def total_reward_for_business_users(tier = :first_tier) 
    return @user.total_reward_for_business_users(tier)
  end
    
  def total_reward_for_premium_users(tier = :first_tier)
    return @user.total_reward_for_premium_users(tier)
  end 

  def total_reward(tier = :first_tier)
    return (total_reward_for_basic_users(tier) + total_reward_for_business_users(tier) + total_reward_for_premium_users(tier))
  end 

  def remaining_jobs_count
    @remaining_jobs_count ||= Delayed::Job.where(queue: 'user_import_queue', last_error: nil).count 
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
  def visible_field?(field, current_user, user)
    #return true if user_signed_in? && user.is?(current_user)
    return user.visible_field?(field) 
  end

  def token_limit(user)

  	role_name = user.role.name

  	if user.premium_user? 
  	  	return 'null'
  	elsif user.business_user?
		   return 1
  	else
		   return 0
  	end	

  end  


  def rating_per_criteria(business) 
      rating_per_criteria_hash = {}
      Rate.where("rateable_id=? and rateable_type = ?" ,business.id,'Business').collect{|t|  rating_per_criteria_hash[t.dimension.to_sym]  = t.stars }
      rating_per_criteria_hash
  end

  def linkedin_url(user)
      user.linkedin_url.blank? ? "javascript:void(0)" : user.linkedin_url
  end  

  def facebook_url(user)
      user.facebook_url.blank? ? "javascript:void(0)" : user.facebook_url
  end

  def twitter_url(user)  
      user.twitter_url.blank? ? "javascript:void(0)" : user.twitter_url
  end

    
end

app/views/admin/users/_all_members.html.erb
<div class="row">
  <div role="main" class="col-md-9">
  	<h3>All Downline Members</h3>

    <div id="referrals">
      <%= render :partial => 'referrals' , :locals => {:downline_members =>@user.downline_members } %>
    </div>

  </div>

  <div class="col-md-3 first_c3">
	   <div class="right_box">
		    <h3 class="right_h">User Detail</h3>
		    
		    <div class="inp_row">	  
			    <p>Username</p>
			    <span><%= @user.name.try(:titleize) %></span>	
		    </div>

		    <div class="inp_row">	  
			    <p>Email</p>
			    <span><%= @user.email %></span>	
		    </div>

		    <div class="inp_row">	  
			    <p>Role</p>
			    <span><%= @user.role_name.try(:titleize) %></span>	
		    </div>	

		    <div class="inp_row">	  
			    <p>Referred By</p>
			    <span><%= @user.affiliate.try(:email) || "None" %></span>	
		    </div>
    

	  	</div>

		<div class="clear"></div>

	  	<div class="right_box">
		    <h3 class="right_h">Referral Detail</h3>
		    
		    <div class="inp_row">
		    	<p>Number Of Referrals</p>
			    <span><%= @user.downline_members.try(:size) %></span>	
		    </div>

		    <div class="inp_row">

		    </div>


		    <div class="inp_row">

		    </div> 

	  	</div>
  </div>
    
  <div class="clear"></div>

</div>

app/views/admin/users/_filters.html.erb
<%= form_tag search_admin_users_path , :method => :get do %>
  <div class="right_box">
    <h3 class="right_h">Filters</h3>
    
    <div class="inp_row">
      <p>Search User</p>
      <span class='hint-message'>By name, email or skills</span>
      <div class="">
        <%= text_field_tag :query ,params[:query],:class=> "filter-attributes form-control" %>
      </div>
      <div class="clear"></div>
    </div>

    <div class="inp_row">
      <p>User Role</p>
      <div class="cell_in1">
        <%= select_tag :role_name , options_for_select(Role.all.collect{ |r| [r.name.titleize, r.name] } , params[:role_name]), :prompt => "All" ,:class=> "filter-attributes form-control"%>
      </div>
      <div class="clear"></div>
    </div>


    <div class="inp_row">
      <div class="cell_in2">
        <%= submit_tag "Filter" , :class=>"button"%>
      </div>
      <div class="clear"></div>
    </div> 
  </div>

<% end %>

app/views/admin/users/_users.html.erb
<div class="users_list digg_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="left_tbl list">
  <table width="647" class="table table-striped table-hover">
    <tr>
      <th>Serial </th>
     <!--  <th>State</th> -->
      <th>Email</th>
      <th>Name</th>
      <th>Business Name</th>
      <th>Role</th>
      <th>Referred By</th>
      <th>City</th>
      <th>State Code</th>
      <th class='user-actions'></th>
    </tr>

    <% @users.each_with_index do |user,index| %>
      <%= render :partial => 'user', :locals => {:user => user, :index => index}%>
    <% end %>    
  </table>
</div>

<div class="users_list digg_pagination">
  <%= will_paginate @users, :container => false %>
</div>


<script type="text/javascript">
    $('#users .digg_pagination a').on('click', function () {
      $.getScript(this.href);
      return false;
    });
</script>

app/views/admin/users/activate.js.erb
$("#<%= dom_id(@user)%>").replaceWith("<%=j render :partial => 'user', :locals => {:user => @user, :index => @index} %>")

app/views/admin/users/claimed.html.erb
<h3>Claimed users</h3>

<div class="left_tbl list">
  <table width="647" class="table table-striped table-hover">
    <tr>
      <th>Serial </th>
     <!--  <th>State</th> -->
      <th>Email</th>
      <th>Name</th>
      <th>Reffering emails</th>
      <th>Claimed at</th>
    </tr>

    <% @claimed_users.each_with_index do |user,index| %>
        <tr>
          <td><a href="javascript:void(0)">#<%= index+1 %></a></td>
          <td><%= link_to user.email , user_path(user.username), :target => "_blank" %></td>
          <td><%= user.business_or_full_name %></td>
          <td><%= user.referred_users.map(&:email) %></td>
          <td><%= user.claimed_at.in_time_zone.strftime("%b %d %Y %I:%M") if user.claimed_at %></td>
        </tr>
    <% end %>    
  </table>
</div>

app/views/admin/users/deactivate.js.erb
$("#<%= dom_id(@user)%>").replaceWith("<%=j render :partial => 'user', :locals => {:user => @user, :index => @index} %>")

app/views/admin/users/edit.html.erb
<% content_for :header do %>
  <div class="title_head">
    <div class="container">
      <div class="col-md-4">
        <p class="admin_h">Admin /</p>
        <h2 class="orders_h">Edit User</h2>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div role="main" class="col-md-9">
    <div id="users">
      <%= render 'form' %>
    </div>
  </div>

  <div class="col-md-3 first_c3">
    <%= render :partial => 'filters'%>
  </div>
    
  <div class="clear"></div>
</div>

app/views/admin/users/import.html.erb
<% content_for :header do %>
    <div class="title_head">
      <div class="container">
        <div class="col-md-4">
          <p class="admin_h">Admin /</p>
          <h2 class="orders_h">Import users</h2>
        </div>
        <div class="col-md-8 users-import">
          <%= link_to 'Import users', import_admin_users_path, class: 'btn btn-default' %>
        </div>        
      </div>
    </div>
<% end %>

<div class="row">
  <div role="main" class="col-md-9">
    <div id="users">
      <%= form_tag upload_csv_admin_users_path, multipart: true do %>
        <div class='row'>
          <div class='col-md-3'>
            <label>Select csv file to import</label>
          </div>
          <div class='col-md-9'>
            <%= file_field_tag :csv, class: 'file' %>
          </div>
        </div>
        
        <div class='row upload-csv'>
          <div class='col-md-12'>
            <%= submit_tag 'Upload', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-3 first_c3">
 
  </div>
    
  <div class="clear"></div>
</div>

app/views/admin/users/index.html.erb
<% content_for :header do %>
    <div class="title_head">
      <div class="container">
        <div class="col-md-4">
          <p class="admin_h">Admin /</p>
          <h2 class="orders_h">Users</h2>
        </div>
        <div class="col-md-8 users-import">
          <div class="col-md-10">
            <%= link_to 'Start hubuco script', start_hubuco_admin_users_path, class: 'btn btn-default' unless @hubuco_script_running %>
          </div> 
          <div class="col-md-2">
            <%= link_to 'Import users', import_admin_users_path, class: 'btn btn-default' %>
          </div>
        </div>        
      </div>
    </div>
<% end %>

<div class="row">
  <div role="main" class="col-md-9">
    <h4 class="">
      Remaining users to process in csv = <%= remaining_jobs_count %>
    </h4>    
    <div id="users">
      <%= render 'users' %>
    </div>
  </div>

  <div class="col-md-3 first_c3">
    <%= render :partial => 'filters'%>
  </div>
    
  <div class="clear"></div>
</div>

app/views/admin/users/index.js.erb
$('#users').html('<%= escape_javascript(render("users")) %>');

app/views/admin/users/recent.html.erb
<% content_for :header do %>
    <div class="title_head">
      <div class="container">
        <div class="col-md-4">
          <p class="admin_h">Admin /</p>
          <h2 class="orders_h">Users</h2>
        </div>
        <div class="col-md-8 users-import">
          <%= link_to 'Import users', import_admin_users_path, class: 'btn btn-default' %>
        </div>        
      </div>
    </div>
<% end %>

<div class="row">
  <div role="main" class="col-md-12">
    <h4 class="">
      Created in last <%= @days %> days
    </h4>    
    <div id="users">
      <%= render 'users' %>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/admin/users/search.html.erb
<% content_for :header do %>
    <div class="title_head">
      <div class="container">
        <div class="col-md-4">
          <p class="admin_h">Search /</p>
          <h2 class="orders_h">Search Result</h2>
        </div>

      </div>
    </div>
<% end %>

<div class="row">
  <div role="main" class="col-md-9">

    <div id="users">
      <%= render 'users' %>
    </div>

  </div>

  <div class="col-md-3 first_c3">
    <%= render :partial => 'filters'%>
  </div>
    
  <div class="clear"></div>


</div>

app/views/admin/users/search.js.erb
$('#users').html('<%= escape_javascript(render("users")) %>');

app/views/admin/users/show.js.erb
$('#referrals').html('<%= escape_javascript(render("referrals")) %>');